services:
  - type: web
    name: api-consumer-usage-analytics-console
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.app.unified_app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
